// auto-generated
const GAMES = [
  {
    "name": "3dish",
    "title": "🌊 TIDEBORNE",
    "tagline": "Un océano. Una luz tenue a lo lejos. Camina hacia ella.",
    "type": "web",
    "play": "https://gavilanbe.github.io/3dish/",
    "repo": "https://github.com/gavilanbe/3dish",
    "thumb": "thumbs/3dish.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "bingo",
    "title": "🎱 Bingo Español (90 bolas)",
    "tagline": "El clásico bingo de 90 bolas, ahora en tu terminal y con voz de cantor.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/bingo",
    "thumb": "thumbs/bingo.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "bug-smash",
    "title": "🐛 Bug Smash",
    "tagline": "Backend contra Frontend: dos jugadores, una hoja de cuaderno y el que pierde se come el ticket.",
    "type": "web",
    "play": "https://gavilanbe.github.io/bug-smash/",
    "repo": "https://github.com/gavilanbe/bug-smash",
    "thumb": "thumbs/bug-smash.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "celda",
    "title": "🗡️ Celda",
    "tagline": "Un action-RPG top-down con alma de Game Boy, en canvas puro y sin una sola dependencia.",
    "type": "web",
    "play": "https://gavilanbe.github.io/celda/",
    "repo": "https://github.com/gavilanbe/celda",
    "thumb": "thumbs/celda.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "chef-game",
    "title": "🍳 ¡Chef!",
    "tagline": "Malabares de cocina: atrapa la comida en la sartén, dórala en su punto justo y sírvela antes de que se queme.",
    "type": "web",
    "play": "https://gavilanbe.github.io/chef-game/",
    "repo": "https://github.com/gavilanbe/chef-game",
    "thumb": "thumbs/chef-game.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "command-wars",
    "title": "⚔️ Command Wars",
    "tagline": "Estrategia táctica por turnos en la terminal, al estilo Advance Wars.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/command-wars",
    "thumb": "thumbs/command-wars.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "dakino",
    "title": "🛒 Dakino: Supermarket Heist",
    "tagline": "Sigilo arcade con vista cenital: cuélate en el supermercado, mangonea el mejor botín y escapa sin que los guardias te pillen.",
    "type": "web",
    "play": "https://gavilanbe.github.io/dakino/",
    "repo": "https://github.com/gavilanbe/dakino",
    "thumb": "thumbs/dakino.jpg",
    "wip": true,
    "kind": "juego"
  },
  {
    "name": "deepresion",
    "title": "📓 Deepresion",
    "tagline": "Un plataformas de garabatos donde recorres las páginas de un cuaderno luchando contra tus propios pensamientos negativos.",
    "type": "web",
    "play": "https://gavilanbe.github.io/deepresion/",
    "repo": "https://github.com/gavilanbe/deepresion",
    "thumb": "thumbs/deepresion.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "dogfy-3d",
    "title": "🐕 Dogfy 3D",
    "tagline": "Un perrito low-poly con sabor a cartucho de Nintendo 64, modelado entero a base de geometría procedural.",
    "type": "web",
    "play": "https://gavilanbe.github.io/dogfy-3d/",
    "repo": "https://github.com/gavilanbe/dogfy-3d",
    "thumb": "thumbs/dogfy-3d.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "dogfy-gb",
    "title": "🐶 Dogfy GB",
    "tagline": "Un endless runner para Game Boy de verdad: tu perrito corre por un suelo infinito esquivando croquetas. ¡Pulsa A para saltar!",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/dogfy-gb",
    "thumb": "thumbs/dogfy-gb.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "dogfy-life",
    "title": "🐕 Dogfy Life",
    "tagline": "Tu mascota virtual en la terminal: aliméntala, juega con ella y mírala crecer.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/dogfy-life",
    "thumb": "thumbs/dogfy-life.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "dogfy-runner",
    "title": "🐕 Dogfy Runner",
    "tagline": "Un endless runner en la terminal: corre, salta y recoge comida natural.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/dogfy-runner",
    "thumb": "thumbs/dogfy-runner.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "doodlaria",
    "title": "📒 DOODLARIA",
    "tagline": "Un JRPG dibujado a mano en las páginas de una libreta.",
    "type": "web",
    "play": "https://gavilanbe.github.io/doodlaria/",
    "repo": "https://github.com/gavilanbe/doodlaria",
    "thumb": "thumbs/doodlaria.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "doodle-quest",
    "title": "✏️ Doodle Quest — El Secreto del Cuaderno",
    "tagline": "Un action-RPG roguelite dibujado a mano sobre papel cuadriculado, donde la muerte es parte del juego.",
    "type": "web",
    "play": "https://gavilanbe.github.io/doodle-quest/",
    "repo": "https://github.com/gavilanbe/doodle-quest",
    "thumb": "thumbs/doodle-quest.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "doodli",
    "title": "✏️ Doodli",
    "tagline": "Un JRPG hecho a mano sobre una página de cuaderno: camina por el papel, habla con los garabatos y entra en combates por turnos con muchísimo \"juice\".",
    "type": "web",
    "play": "https://gavilanbe.github.io/doodli/",
    "repo": "https://github.com/gavilanbe/doodli",
    "thumb": "thumbs/doodli.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "el-oraculo-de-jorge",
    "title": "🔮 El Oráculo de Jorge",
    "tagline": "Misterio, dilemas morales y karma, narrados por un oráculo con voz propia.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/el-oraculo-de-jorge",
    "thumb": "thumbs/el-oraculo-de-jorge.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "gacha-zoo",
    "title": "🐾 Gacha Zoo",
    "tagline": "Una máquina gachapon 3D voxel llena de animalitos coleccionables. ¡Tira de la palanca y a ver qué cae! 🎰",
    "type": "web",
    "play": "https://gavilanbe.github.io/gacha-zoo/",
    "repo": "https://github.com/gavilanbe/gacha-zoo",
    "thumb": "thumbs/gacha-zoo.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "gb-game",
    "title": "🎮 Bestiario del Valle Brezo",
    "tagline": "Un mini-RPG captura-monstruos estilo Game Boy que vive entero dentro de tu terminal: 160x144 píxeles, verde monocromo y chiptune generado al vuelo.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/gb-game",
    "thumb": "thumbs/gb-game.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "gomi",
    "title": "🤖 Machinamon",
    "tagline": "Incuba, afina y cría a tu propio monstruo mecánico en un taller idle de estética GBA.",
    "type": "web",
    "play": "https://gavilanbe.github.io/gomi/",
    "repo": "https://github.com/gavilanbe/gomi",
    "thumb": "thumbs/gomi.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "gotchi",
    "title": "🥚 Gotchi",
    "tagline": "Un Tamagotchi para tu terminal: incuba el huevo, cuida a tu mascota y mírala evolucionar.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/gotchi",
    "thumb": "thumbs/gotchi.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "jub",
    "title": "🥊 Doodle Smash",
    "tagline": "En local:",
    "type": "web",
    "play": "https://gavilanbe.github.io/jub/",
    "repo": "https://github.com/gavilanbe/jub",
    "thumb": "thumbs/jub.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "kaizen",
    "title": "🗼 Kaizen Tower Defense",
    "tagline": "Defiende la ruta, mejora tus torres y aguanta cada oleada. Un Tower Defense web con criaturas estilo Pokémon.",
    "type": "web",
    "play": "https://gavilanbe.github.io/kaizen/",
    "repo": "https://github.com/gavilanbe/kaizen",
    "thumb": "thumbs/kaizen.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "lane-catcher",
    "title": "🏀 Lane Catcher",
    "tagline": "Un arcade de reflejos para la terminal: la bola rebota por tres zonas y tienes que tener la barra en el sitio correcto en cada rebote.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/lane-catcher",
    "thumb": "thumbs/lane-catcher.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "libret",
    "title": "✏️ Libreta",
    "tagline": "Hack & slash de garabatos: una libreta de papel cobra vida y todo lo dibujado quiere matarte.",
    "type": "web",
    "play": "https://gavilanbe.github.io/libret/",
    "repo": "https://github.com/gavilanbe/libret",
    "thumb": "thumbs/libret.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "libreta",
    "title": "✏️ LIBRETA",
    "tagline": "LIBRETA es un hack & slash con estética de cuaderno escolar: papel rayado, margen rojo y un trazo \"hervido\" tipo boceto, todo dibujado en código (sin imágenes ni sprites)",
    "type": "web",
    "play": "https://gavilanbe.github.io/libreta/",
    "repo": "https://github.com/gavilanbe/libreta",
    "thumb": "thumbs/libreta.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "makinamon",
    "title": "🤖 MAKINAMON · Versión Máquina",
    "tagline": "Atrapa robots, entrena criaturas máquina y combate por turnos en un mundo Game Boy Color.",
    "type": "web",
    "play": "https://gavilanbe.github.io/makinamon/",
    "repo": "https://github.com/gavilanbe/makinamon",
    "thumb": "thumbs/makinamon.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "michi",
    "title": "🐈 michi",
    "tagline": "Un gato pixel-art que vive en la parte de abajo de tu terminal mientras la usas.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/michi",
    "thumb": "thumbs/michi.jpg",
    "wip": false,
    "kind": "juguete"
  },
  {
    "name": "monster-battler",
    "title": "👾 Monster Battler",
    "tagline": "Eclosiona, colecciona y combate: un RPG de monstruos de bolsillo que cabe en una pestaña del navegador.",
    "type": "web",
    "play": "https://gavilanbe.github.io/monster-battler/",
    "repo": "https://github.com/gavilanbe/monster-battler",
    "thumb": "thumbs/monster-battler.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "msemmen-clicker",
    "title": "🫓 Msemmen Clicker",
    "tagline": "Toca el msemmen, gana baraka y monta el imperio de la crepe marroquí.",
    "type": "web",
    "play": "https://gavilanbe.github.io/msemmen-clicker/",
    "repo": "https://github.com/gavilanbe/msemmen-clicker",
    "thumb": "thumbs/msemmen-clicker.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "multiblex",
    "title": "🏎️ multiblex",
    "tagline": "Un kart-racer multijugador para la terminal, con cámara estilo Modo 7 de la SNES.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/multiblex",
    "thumb": "",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "nahugavi",
    "title": "🐆 NAHU & GAVI · El Ídolo del Sol",
    "tagline": "Un plataformas 3D de navegador, tributo a los clásicos coleccioneros de los 90.",
    "type": "web",
    "play": "https://gavilanbe.github.io/nahugavi/",
    "repo": "https://github.com/gavilanbe/nahugavi",
    "thumb": "thumbs/nahugavi.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "ofis",
    "title": "🏢 Chibi Office",
    "tagline": "Chibi Office es una experiencia isométrica relajante hecha al 100% con p5.js.",
    "type": "web",
    "play": "https://gavilanbe.github.io/ofis/",
    "repo": "https://github.com/gavilanbe/ofis",
    "thumb": "thumbs/ofis.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "pang",
    "title": "🫧 PANG DELUXE",
    "tagline": "Un tributo a Pang / Buster Bros para tu terminal: revienta bolas con el arpón antes de que te aplasten.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/pang",
    "thumb": "thumbs/pang.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "png-to-svg-app",
    "title": "🖼️➡️📐 Raster → Vector",
    "tagline": "Conversor de imágenes raster (PNG/JPG) a vectores SVG, 100 % en tu navegador.",
    "type": "web",
    "play": "https://gavilanbe.github.io/png-to-svg-app/",
    "repo": "https://github.com/gavilanbe/png-to-svg-app",
    "thumb": "thumbs/png-to-svg-app.jpg",
    "wip": false,
    "kind": "herramienta"
  },
  {
    "name": "poke-autobattler",
    "title": "⚔️ Poké Autobattler",
    "tagline": "Un auto-battler de mochilas estilo Super Auto Pets / TFT en el universo Pokémon: monta tu equipo, activa sinergias y derrota a los 9 Líderes de Gimnasio.",
    "type": "web",
    "play": "https://gavilanbe.github.io/poke-autobattler/",
    "repo": "https://github.com/gavilanbe/poke-autobattler",
    "thumb": "thumbs/poke-autobattler.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "pokechess",
    "title": "♟️ PokéChess — Type Sumo",
    "tagline": "Online: 👉 gavilanbe.github.io/pokechess",
    "type": "web",
    "play": "https://gavilanbe.github.io/pokechess/",
    "repo": "https://github.com/gavilanbe/pokechess",
    "thumb": "thumbs/pokechess.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "pokedefense",
    "title": "🗼 PokéDefense",
    "tagline": "Un tower defense con temática Pokémon: coloca entrenadores, defiende la ruta y conviértete en Campeón.",
    "type": "web",
    "play": "https://gavilanbe.github.io/pokedefense/",
    "repo": "https://github.com/gavilanbe/pokedefense",
    "thumb": "thumbs/pokedefense.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "pokedex",
    "title": "🔴 Pokédex Nacional CLI",
    "tagline": "Una Pokédex interactiva para tu terminal con los Pokémon #001 al #649 (Generaciones I-V): sprites, gritos, minijuegos y mucho más.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/pokedex",
    "thumb": "thumbs/pokedex.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "pokemon-route1",
    "title": "🎵 Pokémon — Ruta 1 (Chiptune)",
    "tagline": "El tema de la Ruta 1 de Pokémon Rojo/Azul, sintetizado desde cero con sonido de Game Boy.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/pokemon-route1",
    "thumb": "thumbs/pokemon-route1.jpg",
    "wip": false,
    "kind": "música"
  },
  {
    "name": "pokemon-terminal",
    "title": "🔴 Pokémon Red Terminal",
    "tagline": "La secuencia inicial de Pokémon Rojo renacida en tu terminal: Pueblo Paleta, el laboratorio del Profesor Oak y la Ruta 1, todo en ASCII a todo color.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/pokemon-terminal",
    "thumb": "thumbs/pokemon-terminal.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "ranota",
    "title": "🐸 RaNota",
    "tagline": "Eres una rana voxel en un mundo cúbico. Salta, mira alrededor y caza moscas con la lengua.",
    "type": "web",
    "play": "https://gavilanbe.github.io/ranota/",
    "repo": "https://github.com/gavilanbe/ranota",
    "thumb": "thumbs/ranota.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "roguelike",
    "title": "🗝️ Crypts of Eternity",
    "tagline": "Doce puertas. Una promesa. Desciende. Sobrevive. Cierra la puerta más profunda.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/roguelike",
    "thumb": "thumbs/roguelike.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "shooter",
    "title": "😈 Terminal DOOM",
    "tagline": "Un FPS estilo DOOM con raycasting renderizado enteramente en tu terminal: tres niveles, llaves de colores, barriles explosivos y SFX procedurales.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/shooter",
    "thumb": "thumbs/shooter.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "short-hike-demo",
    "title": "🏝️ Isla",
    "tagline": "Una pequeña isla para explorar a tu ritmo: trepa, salta, planea y piérdete un rato.",
    "type": "web",
    "play": "https://gavilanbe.github.io/short-hike-demo/",
    "repo": "https://github.com/gavilanbe/short-hike-demo",
    "thumb": "thumbs/short-hike-demo.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "space-battle",
    "title": "🚀 Cosmic Defender",
    "tagline": "Un shoot'em up espacial para la terminal con física de inercia, fuego con gradiente real, oleadas de enemigos y jefes.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/space-battle",
    "thumb": "thumbs/space-battle.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "space-shooter",
    "title": "🛸 Space Shooter",
    "tagline": "Un shoot'em up espacial para la terminal, rápido, con framebuffer propio y audio real.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/space-shooter",
    "thumb": "thumbs/space-shooter.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "spirout",
    "title": "🧚 Spirout",
    "tagline": "Un duende del bosque de cabeza amarilla y antena en espiral, esculpido a base de primitivas con estética Nintendo 64.",
    "type": "web",
    "play": "https://gavilanbe.github.io/spirout/",
    "repo": "https://github.com/gavilanbe/spirout",
    "thumb": "thumbs/spirout.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "sprout-game",
    "title": "SPROUT · y las 8 semillas",
    "tagline": "Una microaventura tipo Zelda, estilo Game Boy, hecha a mano con rectángulos.",
    "type": "web",
    "play": "https://gavilanbe.github.io/sprout-game/",
    "repo": "https://github.com/gavilanbe/sprout-game",
    "thumb": "thumbs/sprout-game.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "sprout-gbc",
    "title": "🌱 SPROUT (Game Boy Color)",
    "tagline": "Port homebrew para Game Boy Color de SPROUT: una aventurilla de acción top-down tipo Zelda, en una ROM .gbc real.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/sprout-gbc",
    "thumb": "",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "srak-l-zit",
    "title": "🫒 Srak l-Zit · سرق الزيت",
    "tagline": "El Atraco del Aceite: una cucaracha ladronzuela contra el oro líquido del Magreb.",
    "type": "web",
    "play": "https://gavilanbe.github.io/srak-l-zit/",
    "repo": "https://github.com/gavilanbe/srak-l-zit",
    "thumb": "thumbs/srak-l-zit.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "stratecorum-terminal",
    "title": "🃏 Stratecorum Terminal",
    "tagline": "Un juego de cartas y estrategia para la terminal, a todo color y sin dependencias externas.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/stratecorum-terminal",
    "thumb": "thumbs/stratecorum-terminal.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "tamamon",
    "title": "🥚 Tamamon",
    "tagline": "Tamamon es un juego idle/clicker de monstruo digital con estética Game Boy + Digivice.",
    "type": "web",
    "play": "https://gavilanbe.github.io/tamamon/",
    "repo": "https://github.com/gavilanbe/tamamon",
    "thumb": "thumbs/tamamon.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "terminal-platformer",
    "title": "🟦 Terminal Platformer",
    "tagline": "Un plataformas clásico que vive enteramente en tu terminal — salta, esquiva y llega a la meta.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/terminal-platformer",
    "thumb": "thumbs/terminal-platformer.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "terminal-tale",
    "title": "💛 Terminal Tale",
    "tagline": "Un RPG de terminal estilo Undertale: esquiva los ataques con tu corazón.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/terminal-tale",
    "thumb": "thumbs/terminal-tale.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "termy",
    "title": "🌸 TERMY",
    "tagline": "Un plataformas de scroll lateral inspirado en Kirby: inhala enemigos, copia sus poderes y recorre un sistema de archivos convertido en mundos.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/termy",
    "thumb": "thumbs/termy.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "undertale_terminal",
    "title": "👾 UNDERSHELL",
    "tagline": "Un RPG de terminal inspirado en Undertale, ambientado dentro de un sistema operativo moribundo.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/undertale_terminal",
    "thumb": "thumbs/undertale_terminal.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "uno",
    "title": "🎴 UNO para la terminal",
    "tagline": "UNO multijugador en Rust: servidor/cliente TCP, bots que rellenan la mesa y una TUI a todo color.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/uno",
    "thumb": "thumbs/uno.jpg",
    "wip": false,
    "kind": "juego"
  },
  {
    "name": "wirefox",
    "title": "🚀 Wirefox",
    "tagline": "Un rail shooter pseudo-3D en ASCII para la terminal — vuela hacia el infinito, esquiva asteroides y derriba jefes.",
    "type": "terminal",
    "play": "",
    "repo": "https://github.com/gavilanbe/wirefox",
    "thumb": "thumbs/wirefox.jpg",
    "wip": false,
    "kind": "juego"
  }
];
